export const errorCodes = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACTIVATION_CODE_INVALID: "ACTIVATION_CODE_INVALID",
  ACTIVATION_CODE_EXPIRED: "ACTIVATION_CODE_EXPIRED",
  ACTIVATION_CODE_REDEEMED: "ACTIVATION_CODE_REDEEMED",
  ACTIVATION_CODE_ROLE_CONFLICT: "ACTIVATION_CODE_ROLE_CONFLICT",
  CLIENT_NO_TASK_CREDITS: "CLIENT_NO_TASK_CREDITS",
  TASK_INVALID_URL: "TASK_INVALID_URL",
  TASK_ALREADY_CLAIMED: "TASK_ALREADY_CLAIMED",
  TASK_CLAIM_WINDOW_EXPIRED: "TASK_CLAIM_WINDOW_EXPIRED",
  TASK_COMPLETION_WINDOW_EXPIRED: "TASK_COMPLETION_WINDOW_EXPIRED",
  TASK_INVALID_STATE: "TASK_INVALID_STATE",
  TASK_NOT_OWNED: "TASK_NOT_OWNED",
  SCANNER_ALREADY_HAS_ACTIVE_TASK: "SCANNER_ALREADY_HAS_ACTIVE_TASK",
  SCANNER_OFFLINE: "SCANNER_OFFLINE",
  PAYOUT_INSUFFICIENT_BALANCE: "PAYOUT_INSUFFICIENT_BALANCE",
  PAYOUT_BELOW_MINIMUM: "PAYOUT_BELOW_MINIMUM",
  PAYOUT_INVALID_DESTINATION: "PAYOUT_INVALID_DESTINATION",
  DISPUTE_ALREADY_OPEN: "DISPUTE_ALREADY_OPEN",
  TELEGRAM_NOT_CONFIGURED: "TELEGRAM_NOT_CONFIGURED",
  TELEGRAM_WEBHOOK_FAILED: "TELEGRAM_WEBHOOK_FAILED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = keyof typeof errorCodes;

export class DomainError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly statusCode = 400,
    public readonly details: unknown = null
  ) {
    super(message);
  }
}
